### ISSUE TITLE
.mget() works incorrectly

### ISSUE THREAD

**Issue by jpodwys** [darrylwest/mock-redis-client#1]
Thank you for attempting to provide a more robust mock than exists elsewhere. I'm having an issue.

Redis' `.mget()` returns an array of values in respective order to the array of keys requested. It also returns `null` for the value of a key that was not found.

Example:

``` javascript
myCache.mget(['key1', ' key2', ' key3'], function (err, response){
  //response is something like ['value1', 'value2', null]
});
```

I've found two issues with mock-redis-client's implementation of `.mget()`:
- The array of values returned is in the reverse order the requested keys were listed in
- `null` values are omitted

**Comment by darrylwest** [comment]
Thanks for the feedback.  I'll give it a look

**Comment by jpodwys** [comment]
I made a PR, but I did not update your tests. If you update the tests, it should be good to go.

**Comment by darrylwest** [comment]
great, thanks
